
'use client';

import { SessionProvider } from 'next-auth/react';
import AuthProvider from './AuthProviders/AuthProvider';
import Navbar from './Navigation/Navbar';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "CourseMaster",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-11/12 mx-auto space-y-5">
        <SessionProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
